// packages/vue/src/QirtaasRenderer.vue
<script setup lang="ts">
// Read-only sibling of QirtaasEditor: mounts @qirtaas/core's renderer and only
// tracks live theme changes. Exactly one auth source (getSignature | getToken |
// shareToken) must be supplied — the core mount() enforces that.
import { ref, onMounted, onBeforeUnmount, watch } from "vue";
import { createQirtaasClient } from "@qirtaas/core";
import type {
  RendererInstance,
  RendererMountOptions,
  Locale,
  Theme,
  ErrorCode,
} from "@qirtaas/core";

const props = defineProps<{
  apiUrl?: string;
  documentId?: string;
  locale?: Locale;
  theme?: Theme;
  getSignature?: RendererMountOptions["getSignature"];
  getToken?: RendererMountOptions["getToken"];
  shareToken?: string;
}>();

const emit = defineEmits<{
  ready: [];
  error: [code: ErrorCode, detail?: unknown];
}>();

const host = ref<HTMLElement | null>(null);
let instance: RendererInstance | null = null;

onMounted(() => {
  if (!host.value) return;
  // Renderer auth is per-call (getSignature/getToken/shareToken); the client
  // only carries apiUrl, so no getToken is configured here.
  const client = createQirtaasClient({ apiUrl: props.apiUrl });
  instance = client.mountRenderer(host.value, {
    documentId: props.documentId,
    locale: props.locale,
    theme: props.theme,
    getSignature: props.getSignature,
    getToken: props.getToken,
    shareToken: props.shareToken,
    onReady: () => emit("ready"),
    onError: (code, detail) => emit("error", code, detail),
  });
});

watch(
  () => props.theme,
  (theme) => {
    if (theme) instance?.setTheme(theme);
  }
);

onBeforeUnmount(() => {
  instance?.destroy();
  instance = null;
});

defineExpose({
  setTheme: (theme: Theme) => instance?.setTheme(theme),
});
</script>

<template>
  <div ref="host"></div>
</template>

// packages/react/src/QirtaasRenderer.ts
// Read-only React adapter for @qirtaas/core's renderer. Exactly one auth source
// (getSignature | getToken | shareToken) must be supplied; core enforces it.
import {
  createElement,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
} from "react";
import { createQirtaasClient } from "@qirtaas/core";
import type {
  RendererInstance,
  RendererMountOptions,
  Locale,
  Theme,
  ErrorCode,
} from "@qirtaas/core";

export interface QirtaasRendererProps {
  apiUrl?: string;
  documentId?: string;
  locale?: Locale;
  theme?: Theme;
  getSignature?: RendererMountOptions["getSignature"];
  getToken?: RendererMountOptions["getToken"];
  shareToken?: string;
  onReady?: () => void;
  onError?: (code: ErrorCode, detail?: unknown) => void;
}

export interface QirtaasRendererHandle {
  setTheme: (theme: Theme) => void;
}

export const QirtaasRenderer = forwardRef<
  QirtaasRendererHandle,
  QirtaasRendererProps
>(function QirtaasRenderer(props, ref) {
  const host = useRef<HTMLDivElement>(null);
  const instance = useRef<RendererInstance | null>(null);
  const latest = useRef(props);
  latest.current = props;

  useEffect(() => {
    if (!host.current) return;
    const p = latest.current;
    // Renderer auth is per-call; the client only carries apiUrl.
    const client = createQirtaasClient({ apiUrl: p.apiUrl });
    const inst = client.mountRenderer(host.current, {
      documentId: p.documentId,
      locale: p.locale,
      theme: p.theme,
      getSignature: p.getSignature,
      getToken: p.getToken,
      shareToken: p.shareToken,
      onReady: () => latest.current.onReady?.(),
      onError: (code, detail) => latest.current.onError?.(code, detail),
    });
    instance.current = inst;
    return () => {
      inst.destroy();
      instance.current = null;
    };
  }, []);

  useEffect(() => {
    if (props.theme) instance.current?.setTheme(props.theme);
  }, [props.theme]);

  useImperativeHandle(
    ref,
    () => ({ setTheme: (theme: Theme) => instance.current?.setTheme(theme) }),
    []
  );

  return createElement("div", { ref: host });
});
